name: Manual trigger

on:
  push:
    branches:
      - franco-pagos-qa
  workflow_dispatch:

jobs:
  ci-pagos-qa:
    if: github.ref == 'refs/heads/franco-pagos-qa' || github.event.inputs.environment == 'QA'
    runs-on: ubuntu-latest

