name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Seleccione el branch de destino'
        required: true

jobs:
  run-on-selected-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow on selected branch
        if: github.ref == 'refs/heads/${{ github.event.inputs.branch }}'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/dispatches
          ref: ${{ github.event.inputs.branch }}
